### PR TITLE
Flash Attention 2: Save mask application if block is not in boundary

### PR DESCRIPTION
**Pull request by hypnopump**
Skips mask application is block is not the boundary block.

### CODE REVIEW

**Comment by iclementine** [comment]
Hey, do you find this improves the speed? 
I used to add some fine-grained control about masking.

Static condition: `DIVISIBLE_M` and `DIVISIBLE_N`. If we know that m, n  is divisible by `BLOCK_M` and `BLOCK_N`, respectively, we can skip masking with triton's constexpr as condition. This removes masking at compile time.

Runtime condition: Even when neither `DIVISIBLE_M` and `DIVISIBLE_N` is true, only the last tile requires masking, both for loading, and some other computation.  

I find that static conditioning on masking improves the performances while runtime conditioning does not. We can also think about the simple pointwise computation kernel in CUDA.

```c
__global__
void saxpy(int n, float a, float *x, float *y)
{
  int i = blockIdx.x*blockDim.x + threadIdx.x;
  if (i < n) y[i] = a*x[i] + y[i];
}
```

Although we can make finer control about masking, say, "only the last CTA should apply maksing", or only the "last warp should apply maksing". But to determine whether the thread is in the last CTA or last warp requires some extra computation at runtime. So this may not improve performance. I need some performance data to ensure that this would help.


As to the style, I prefer the dummy layout that uses different blocks in `if-else statement`s instead of `if-else expression`s to remind me that static conditions (conditions on `tl.constexpr`)  are like template parameters or Macros `#if #else #endif` in c++. It is compile-time-effective rather than runtime-effective. It may look ugly, but it leaves some visual traces that it is not a usual if-else.

**Comment by iclementine** [comment]
Also I found some bugs in triton compiler that is may bot compiles static conditions or static-and-dynamic conditions correctly.

For example:

1. `A` and `B` are both `tl.constexpr`, but triton would not necessarily treat `A and not B` as a static condition.
2. `A` is a `tl.constexpr` while `b` is not. Triton compiler cannot correctly perform logical shortcut when compiling.

**Comment by hypnopump** [comment]
You were right about the ifs. Triton compiler really doesn't like dynamic typing (None or Tensor) and boolean logic; so i reformulated the ifs to be closer to the original. I tried the resulting code on my modest RTX 2060Ti 12Gb, and it seems it's a bit faster now.

Main branch: 
Screenshot from 2023-12-13 23-36-45

And just when checking the last block: 
Screenshot from 2023-12-13 23-36-57

**Comment by iclementine** [comment]
I've tested your commit on A100 with `divisible_m` and `divisible_n`, which is included in the benchmark. The performance is about the same as the current implemention.

But when tesing with non-divisible m and non divisible_n, the code fails to compile. You can reproduce this by add a `N_CTX -= 10` into https://github.com/FlagOpen/FlagAttention/blob/53ce09c40fc23a2b45a4b7e42b982e77c086afb3/benchmark/flash_benchmark.py#L49 .

图片

Maybe I should add more unittesting cases to ensure it runs.

**Comment by hypnopump** [comment]
ah yes im closing this, seems is triton tries to analyze things inside dynamic if-elses; only way to have a bool value the compiler "respects" seems to be passing it to the whole kernel grid, as `DIVISIBLE_M`, `DIVISIBLE_N`

**Pull request closed without merging**
